version: '3.1'

services:
  db:
    image: postgres:14.1-alpine
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - '5435:5432'
    volumes:
      - test-db:/var/lib/postgresql/data
volumes:
  test-db:
    driver: local
